version: '3.4'

services:

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "45100:80"

  mariadb:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - "43306:3306"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"